# Databricks notebook source
# COMMAND ----------
# MAGIC %md
# MAGIC # 04 — Gold (Modelo Dimensional Ralph Kimball)
# MAGIC
# MAGIC Star schema: `dim_carro`, `dim_cliente`, `dim_localidade`, `dim_tempo`, `fato_sinistro`.
# MAGIC Dimensões usam MERGE INTO (SCD Type 1). Fato é populada por INSERT com JOIN.

# COMMAND ----------
# Lê silver e cria temp views
SILVERS = [
    "apolice", "carro", "cliente", "endereco", "estado", "marca",
    "modelo", "municipio", "regiao", "sinistro", "telefone",
]

for t in SILVERS:
    spark.read.format("delta").table(f"silver.{t}").createOrReplaceTempView(t)

# COMMAND ----------
# DDL das dimensões e fato (idempotente)
spark.sql("""
CREATE TABLE IF NOT EXISTS gold.dim_carro (
  SK_CARRO bigint GENERATED BY DEFAULT AS IDENTITY,
  PLACA    string,
  MARCA    string,
  MODELO   string,
  COR      string,
  ANO      int,
  CHASSI   string
) USING DELTA
""")

spark.sql("""
CREATE TABLE IF NOT EXISTS gold.dim_cliente (
  SK_CLIENTE      bigint GENERATED BY DEFAULT AS IDENTITY,
  CODIGO_CLIENTE  int,
  NOME            string,
  CPF             string,
  SEXO            string,
  DATA_NASCIMENTO date
) USING DELTA
""")

spark.sql("""
CREATE TABLE IF NOT EXISTS gold.dim_localidade (
  SK_LOCALIDADE    bigint GENERATED BY DEFAULT AS IDENTITY,
  CODIGO_MUNICIPIO int,
  NOME_MUNICIPIO   string,
  NOME_ESTADO      string,
  NOME_REGIAO      string
) USING DELTA
""")

spark.sql("""
CREATE TABLE IF NOT EXISTS gold.fato_sinistro (
  FK_TEMPO       date,
  FK_LOCALIDADE  bigint,
  FK_CARRO       bigint,
  FK_CLIENTE     bigint,
  QTDE_SINISTRO  int
) USING DELTA
""")

# COMMAND ----------
# MERGE INTO dim_carro (SCD1)
spark.sql("""
WITH carros_relacional AS (
  SELECT placa, nome_marca, nome_modelo, cor, ano, chassi
  FROM carro c
  INNER JOIN modelo mo ON c.codigo_modelo = mo.codigo_modelo
  INNER JOIN marca  ma ON mo.codigo_marca = ma.codigo_marca
)
MERGE INTO gold.dim_carro AS d
USING carros_relacional AS r
ON d.placa = r.placa
WHEN MATCHED AND (
       d.marca  <> r.nome_marca
    OR d.modelo <> r.nome_modelo
    OR d.cor    <> r.cor
    OR d.ano    <> r.ano
    OR d.chassi <> r.chassi
) THEN UPDATE SET
       marca  = r.nome_marca,
       modelo = r.nome_modelo,
       cor    = r.cor,
       ano    = r.ano,
       chassi = r.chassi
WHEN NOT MATCHED THEN INSERT (placa, marca, modelo, cor, ano, chassi)
       VALUES (r.placa, r.nome_marca, r.nome_modelo, r.cor, r.ano, r.chassi)
""")

# COMMAND ----------
# MERGE INTO dim_cliente (SCD1)
spark.sql("""
WITH cliente_relacional AS (
  SELECT codigo_cliente, nome, cpf, sexo, data_nascimento FROM cliente
)
MERGE INTO gold.dim_cliente AS d
USING cliente_relacional AS r
ON d.codigo_cliente = r.codigo_cliente
WHEN MATCHED AND (
       d.nome            <> r.nome
    OR d.cpf             <> r.cpf
    OR d.sexo            <> r.sexo
    OR d.data_nascimento <> r.data_nascimento
) THEN UPDATE SET
       nome            = r.nome,
       cpf             = r.cpf,
       sexo            = r.sexo,
       data_nascimento = r.data_nascimento
WHEN NOT MATCHED THEN INSERT (codigo_cliente, nome, cpf, sexo, data_nascimento)
       VALUES (r.codigo_cliente, r.nome, r.cpf, r.sexo, r.data_nascimento)
""")

# COMMAND ----------
# MERGE INTO dim_localidade (SCD1)
spark.sql("""
WITH localidade_relacional AS (
  SELECT codigo_municipio, nome_municipio, nome_estado, nome_regiao
  FROM municipio m
  INNER JOIN estado e ON m.codigo_estado = e.codigo_estado
  INNER JOIN regiao r ON e.codigo_regiao = r.codigo_regiao
)
MERGE INTO gold.dim_localidade AS d
USING localidade_relacional AS r
ON d.codigo_municipio = r.codigo_municipio
WHEN MATCHED AND (
       d.nome_municipio <> r.nome_municipio
    OR d.nome_estado    <> r.nome_estado
    OR d.nome_regiao    <> r.nome_regiao
) THEN UPDATE SET
       nome_municipio = r.nome_municipio,
       nome_estado    = r.nome_estado,
       nome_regiao    = r.nome_regiao
WHEN NOT MATCHED THEN INSERT (codigo_municipio, nome_municipio, nome_estado, nome_regiao)
       VALUES (r.codigo_municipio, r.nome_municipio, r.nome_estado, r.nome_regiao)
""")

# COMMAND ----------
# dim_tempo — geração por range
data_inicial = "2023-01-01"
data_final   = "2026-12-31"
num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]

df_calendario = (
    spark.range(0, num_dias + 1)
         .selectExpr(f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS Data")
)

df_tempo = df_calendario.selectExpr(
    "Data",
    "year(Data) AS Ano",
    "month(Data) AS Mes",
    """CASE month(Data)
        WHEN 1 THEN 'JANEIRO'   WHEN 2 THEN 'FEVEREIRO' WHEN 3 THEN 'MARCO'
        WHEN 4 THEN 'ABRIL'     WHEN 5 THEN 'MAIO'      WHEN 6 THEN 'JUNHO'
        WHEN 7 THEN 'JULHO'     WHEN 8 THEN 'AGOSTO'    WHEN 9 THEN 'SETEMBRO'
        WHEN 10 THEN 'OUTUBRO'  WHEN 11 THEN 'NOVEMBRO' WHEN 12 THEN 'DEZEMBRO'
       END AS NomeMes""",
    "day(Data) AS Dia",
    """CASE dayofweek(Data)
        WHEN 1 THEN 'DOMINGO'       WHEN 2 THEN 'SEGUNDA-FEIRA'
        WHEN 3 THEN 'TERCA-FEIRA'   WHEN 4 THEN 'QUARTA-FEIRA'
        WHEN 5 THEN 'QUINTA-FEIRA'  WHEN 6 THEN 'SEXTA-FEIRA'
        WHEN 7 THEN 'SABADO'
       END AS NomeDiaSemana""",
    "dayofweek(Data) AS NumeroDiaSemana",
)

df_tempo.write.mode("overwrite").saveAsTable("gold.dim_tempo", format="delta")
print(f"gold.dim_tempo populada ({df_tempo.count()} dias)")

# COMMAND ----------
# Recarregar dimensões em variáveis pra fato
df_apolice  = spark.read.format("delta").table("silver.apolice")
df_sinistro = spark.read.format("delta").table("silver.sinistro")
df_cliente  = spark.read.format("delta").table("silver.cliente")
df_apolice.createOrReplaceTempView("apolice")
df_sinistro.createOrReplaceTempView("sinistro")
df_cliente.createOrReplaceTempView("cliente")

# COMMAND ----------
# Popular fato_sinistro
spark.sql("TRUNCATE TABLE gold.fato_sinistro")

spark.sql("""
WITH apolice_cliente AS (
  SELECT a.codigo_cliente, a.placa
  FROM apolice a
  INNER JOIN cliente c ON a.codigo_cliente = c.codigo_cliente
)
INSERT INTO gold.fato_sinistro
SELECT dtem.Data           AS FK_TEMPO,
       dloc.sk_localidade  AS FK_LOCALIDADE,
       dcar.sk_carro       AS FK_CARRO,
       dcli.sk_cliente     AS FK_CLIENTE,
       COUNT(1)            AS QTDE_SINISTRO
FROM sinistro s
INNER JOIN gold.dim_carro      dcar ON s.placa            = dcar.placa
INNER JOIN apolice_cliente     ac   ON ac.placa           = s.placa
INNER JOIN gold.dim_cliente    dcli ON ac.codigo_cliente  = dcli.codigo_cliente
INNER JOIN gold.dim_localidade dloc ON s.local_sinistro   = dloc.codigo_municipio
INNER JOIN gold.dim_tempo      dtem ON s.data_sinistro    = dtem.Data
GROUP BY dtem.Data, dloc.sk_localidade, dcar.sk_carro, dcli.sk_cliente
""")

# COMMAND ----------
# MAGIC %sql SELECT COUNT(*) AS total FROM gold.fato_sinistro;

# COMMAND ----------
# MAGIC %sql SHOW TABLES IN gold;
